version: '3.8'

services:
  frontend:
    build:
      context: ./  # Path to the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container port 80 to host port 3000
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
